# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'STG'
    subscriptionId: 'f1eb856e-d060-45c8-957b-bb6ed6516d84'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'APIM-POC'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName APIM-POC -linkedTemplateUri https://raw.githubusercontent.com/HowlinSammy/MattK-APIM/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'